### ISSUE TITLE
js 代码重复

### ISSUE THREAD

**Issue by HuberWong** [roy-tian/learning-area#12]
在[笑话机的main.js](https://github.com/roy-tian/learning-area/blob/master/javascript/introduction-to-js-1/assessment-finished/main.js)文件中，第 24 与第 35 行代码相同，是 `Shift` + `Alt` + `↓` 按秃噜了吗😂

**Comment by roy-tian** [comment]
兄弟，第24行是
`newStory = newStory.replace(':insertx:', xItem);`
第35行是
`const weight = Math.round(140 * 2.20462) + ' 磅';`
我感觉，你的意思是第24行和第25行重复了吧。😂
但是，这两行的作用是不一样的，分别修改了`storyText`里前后两次出现的主人公的名字。
你可以参考一下`String.prototype.replace()`和`String.prototype.replaceAll()`的文档。🙂
另外我复制1行都用的`yyp`哦，复制3行就是`yy3p`。😂
