### ISSUE TITLE
mdn-examples/html/site-structure/index.html页面52、54行乱码了

### ISSUE THREAD

**Issue by WITCHERMASTER3** [roy-tian/learning-area#2]

**Comment by roy-tian** [comment]
这是一首歌曲，歌词讲的是一个古老的童话故事。

从前有一座城市名叫【䥰龘䰕䘋㽌䇁䵄䵻䬛蟿䆉㖀】城

国王的女儿名叫【䥸䝟䳮䟑䎘䫱䉷䰯䕈䟐䬝】公主。

有一只邪恶的巨龙名叫【㱎䖘䵈䶁䘔䶑䘓鋱䩳䵷㒪䪉䉥】掠走了公主。

这时一位英雄名叫【龘䶛䨻䎱㸞蚮䡶䴞䴝䯬䬛䰕㹚】打败了巨龙，救回了公主。

后来英雄和公主就开始了没羞没臊的幸福生活。

推荐到 [bilibili](https://www.bilibili.com/video/av10259571&seid=15367188488765668853) 或 [5sing](http://5sing.kugou.com/fc/15917354.html) 收听。

当然这里内容是次要的，主要是这些 HTML 元素的用法 :)

请使用 utf-8 编码。

感谢 @WITCHERMASTER3 朋友。
