### ISSUE TITLE
mdn-examples/html/planets-data/start.zip里，txt文档中的column被翻译成行了

### ISSUE THREAD

**Issue by Wood-Cube** [roy-tian/learning-area#3]
![image](https://user-images.githubusercontent.com/38563904/60064114-f8826e80-9731-11e9-9dc1-5689f0b520ed.png)
辛苦了

**Comment by Wood-Cube** [comment]
试了一下那个pull request功能不知道对不对

**Comment by roy-tian** [comment]
感谢 @Wood-Cube 朋友，你也辛苦了:)
