### ISSUE TITLE
“查找并解决 JavaScript 代码的错误”章节下链接失效

### ISSUE THREAD

**Issue by Ash1One** [roy-tian/learning-area#7]
https://wiki.developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/What_went_wrong
该章节下“一个出错的示例”部分中的`在线运行`超链接失效了。

`在线运行`失效的链接是：
https://roy-tian.github.io/mdn-examples/javascript/number-guessing-game/number-game-errors.html

**Comment by roy-tian** [comment]
已修正，谢谢反馈。
