### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Liuyan611** [roy-tian/learning-area#9]
when I click a "raw" button, the firfox can't copy it properly. It jumps to error pages.

**Comment by Liuyan611** [comment]
OS:window
Brower:Firefox

**Comment by roy-tian** [comment]
如果你是在国内用 Github，点击 raw 下载不了东西是正常的。

**Comment by Liuyan611** [comment]
好的，谢谢。但是我以前可以下载的。也是用的国内的Github
